import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
   return (
    <html lang="pt-BR">
      <body className="flex flex-col min-h-screen">
        <header className="text-white relative py-4 px-4 flex items-center justify-center" style={{ backgroundColor: '#008B8C' }}>
          <img src="/images/logo.png" alt="Logo" className="h-20 mx-auto"/>
          
          <div className="absolute right-4 inset-y-0 flex items-center">
            <img src="/images/avatar.svg" alt="Avatar" className="h-8 w-8 rounded-full "/>
          </div>
        </header>

        
        <main className="flex-1 p-4 bg-gray-50">{children}</main>

     
        <footer className="bg-teal-700 text-white text-xs text-center p-2">
          Este aplicativo é fictício e não possui qualquer vínculo com instituição financeira real.
        </footer>
      </body>
    </html>
  );
}
